{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "9cc19820-0a6f-4da0-9838-4be9a62f1c9a",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "from selenium import webdriver\n",
    "from bs4 import BeautifulSoup\n",
    "import time\n",
    "from selenium.webdriver.common.by import By\n",
    "from selenium.webdriver.support.ui import WebDriverWait\n",
    "from selenium.webdriver.support import expected_conditions as EC"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "2140124c-b4a0-4ae2-b2fe-45161cd6fd62",
   "metadata": {},
   "outputs": [],
   "source": [
    "# URL of the Amazon search results page\n",
    "url = 'https://www.flipkart.com/search?q=lenovo%20legion&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "77d56026-dd14-4bb6-8ec3-5bcae402c93b",
   "metadata": {},
   "outputs": [],
   "source": [
    "def switch_tab(source,tab_index):\n",
    "    link = source.get('href')\n",
    "    driver.execute_script(f'window.open(\"{link}\", \"_blank\");')\n",
    "\n",
    "    # Wait for the new window to open and then switch to it\n",
    "    WebDriverWait(driver, 10).until(lambda d: len(d.window_handles) > tab_index)\n",
    "    driver.switch_to.window(driver.window_handles[tab_index])\n",
    "\n",
    "    # Wait for the new tab to load its content\n",
    "    WebDriverWait(driver, 10).until(\n",
    "        EC.presence_of_element_located((By.CLASS_NAME, 'fonts-loaded'))\n",
    "    )\n",
    "\n",
    "    # Get the HTML content of the new tab\n",
    "    new_tab_content = driver.page_source\n",
    "    soup = BeautifulSoup(new_tab_content, 'html.parser')\n",
    "\n",
    "    return soup"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "ba333554-963b-4b3c-8c74-34dd1aec9bfe",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Set up the Selenium WebDriver\n",
    "driver = webdriver.Chrome()\n",
    "driver.maximize_window()\n",
    "\n",
    "# Load the page\n",
    "driver.get(url)\n",
    "\n",
    "# Wait for the page to fully load\n",
    "time.sleep(5)\n",
    "\n",
    "# Get the HTML content of the page\n",
    "html_content = driver.page_source\n",
    "\n",
    "# Parse the HTML with BeautifulSoup\n",
    "soup = BeautifulSoup(html_content, 'html.parser')\n",
    "\n",
    "# Find elements containing product information\n",
    "products = soup.find_all('a', rel='noopener noreferrer', limit=10)\n",
    "\n",
    "data = []\n",
    "\n",
    "for product in products:\n",
    "    product_details = {}\n",
    "    name = product.find('div', class_='_4rR01T')\n",
    "    name = name.text if name else \"No name available\"\n",
    "\n",
    "    # Extract the price of the product\n",
    "    price = product.find('div', class_='_30jeq3 _1_WHN1')\n",
    "    price = price.text if price else \"No price available\"\n",
    "\n",
    "    # Extract the rating of the product\n",
    "    rating = product.find('div', class_='_3LWZlK')\n",
    "    rating = rating.text if rating else \"No rating available\"\n",
    "\n",
    "    num_ratings_reviews_container = product.find('span', class_='_2_R_DZ')\n",
    "    if num_ratings_reviews_container:\n",
    "        ratings_reviews_text = num_ratings_reviews_container.get_text().strip()\n",
    "        \n",
    "        # Split the text to isolate ratings and reviews\n",
    "        ratings_text, reviews_text = ratings_reviews_text.split('&')\n",
    "        \n",
    "        # Extract just the numbers\n",
    "        num_ratings = ''.join(filter(str.isdigit, ratings_text))\n",
    "        num_reviews = ''.join(filter(str.isdigit, reviews_text))\n",
    "    else:\n",
    "        num_ratings = \"No ratings\"\n",
    "        num_reviews = \"No reviews\"\n",
    "\n",
    "    # print(f\"Name: {name}\")\n",
    "    # print(f\"Price: {price}\")\n",
    "    # print(f\"Rating: {rating}\")\n",
    "    # print(f\"Number of Ratings: {num_ratings}\")\n",
    "    # print(f\"Number of Reviews: {num_reviews}\")\n",
    "    # print('-' * 50)\n",
    "    \n",
    "    product_details['Product Name'] = name\n",
    "    product_details['Price'] = price\n",
    "    product_details['Rating'] = rating\n",
    "    product_details['Number of Ratings'] = num_ratings\n",
    "    product_details['Number of Reviews'] = num_reviews\n",
    "    if num_reviews != \"No reviews\" and num_reviews != \"0\":\n",
    "        soup = switch_tab(product,1)\n",
    "\n",
    "        # Find the element with the reviews or link to reviews\n",
    "        div_element = soup.find('div', class_='col JOpGWq')\n",
    "\n",
    "        if div_element:\n",
    "            # Find all <a> tags within the div\n",
    "            all_a_tags = div_element.find_all('a')\n",
    "            # Check if there are any <a> tags\n",
    "            if len(all_a_tags) > 10:\n",
    "                # Get the last <a> tag\n",
    "                last_a_tag = all_a_tags[-1]\n",
    "\n",
    "                soup = switch_tab(last_a_tag,2)\n",
    "\n",
    "                reviews_container = soup.find_all('div',class_='col _2wzgFH K0kLPL')\n",
    "                review_summary_list = []\n",
    "                review_details_list = []\n",
    "                for review in reviews_container:\n",
    "                    review_summary = review.find('p',class_='_2-N8zT').text if review.find('p',class_='_2-N8zT') else \"No summary\"\n",
    "                    review_details = review.find('div',class_='t-ZTKy').text if review.find('div',class_='t-ZTKy') else \"No details\"\n",
    "                    review_summary_list.append(review_summary)\n",
    "                    review_details_list.append(review_details)\n",
    "                    # print(f\"{reviews_container.index(review)}. review_summary: {review_summary}\")\n",
    "                    # print(f\"{reviews_container.index(review)}. review_details: {review_details}\")\n",
    "                product_details['Review Summary'] = review_summary_list\n",
    "                product_details['Review Details'] = review_details_list\n",
    "                driver.close()\n",
    "            else:\n",
    "                review_summary_list = []\n",
    "                review_details_list = []\n",
    "                reviews_summary_container = soup.find_all('p',class_='_2-N8zT')\n",
    "                for reviews_summary in reviews_summary_container:\n",
    "                    reviews_summary = reviews_summary.text\n",
    "                    review_summary_list.append(reviews_summary)\n",
    "                #     # print(f\"{reviews_summary_container.index(reviews_summary)}. review_summary: {review_summary}\")\n",
    "                reviews_details_container = soup.find_all('div',class_='t-ZTKy')\n",
    "                for review_details in reviews_details_container:\n",
    "                    # print(reviews_details_container.index(review_details))\n",
    "                    review_details = review_details.text\n",
    "                    review_details_list.append(review_details)\n",
    "                    # print(f\". review_details: {review_details}\")\n",
    "                product_details['Review Summary'] = review_summary_list\n",
    "                product_details['Review Details'] = review_details_list\n",
    "\n",
    "            # print('-' *50)\n",
    "            \n",
    "            driver.switch_to.window(driver.window_handles[1])\n",
    "            driver.close()\n",
    "        driver.switch_to.window(driver.window_handles[0])\n",
    "    data.append(product_details)\n",
    "\n",
    "# Close the browser\n",
    "driver.quit()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "affe1cfa-9915-4d15-b9b7-85e6865d4239",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[{'Product Name': 'Lenovo IdeaPad Gaming 3 AMD Ryzen 5 Hexa Core 7535HS - (16 GB/512 GB SSD/Windows 11 Home/4 GB Graphics...',\n",
       "  'Price': '₹56,990',\n",
       "  'Rating': '4.3',\n",
       "  'Number of Ratings': '68',\n",
       "  'Number of Reviews': '8',\n",
       "  'Review Summary': ['Classy product',\n",
       "   'Worth the money',\n",
       "   'Horrible',\n",
       "   'Best in the market!',\n",
       "   'Super!',\n",
       "   'Simply awesome',\n",
       "   'Simply awesome',\n",
       "   'Excellent'],\n",
       "  'Review Details': ['First Impression: Great build no wobble, full fledged 70 watt RTX2050 gives nearly 3050 75w level performance. 16gb DDR5 ram. 7535HS is good. Only cons are: SSD maxes out at 3500/2000mb/s, though upgradation to a gen4 2280 SSD is possible. And no Ms office. Will update more with timeREAD MORE',\n",
       "   'Overall the product is really nice. Lenovo has included some tweaking features. The only problem that I felt is with the hinge. The laptop screen wobble sometimes.READ MORE',\n",
       "   'Lenovo worst company I purchased this laptop and from 2nd day trackpad started auto clicking and lagging I will never forgive lenovo for breaking my dream of purchasing first good laptopREAD MORE',\n",
       "   'great build and performance  of every segment rtx 2050 works  smoothly with tgp of 70w and ddr5 16gb ram just on topREAD MORE',\n",
       "   \"Bought it at 53k at sale. 16gb DDR5 Ram (dual channel)Rtx 2050 (full 70 watt tgp) will match 75 watt 3050 as processor is also goodBattery is a let down though but I don't expect it to be that good...READ MORE\",\n",
       "   'Good product and svperipherals  seller has given right productREAD MORE',\n",
       "   \"It's performance is really good , but disappointed by screen and battery backup rest overall with price it's a good choice.READ MORE\",\n",
       "   'Awesome product and performs well to my expectation at this price point. only the battery does not last long as expected.Of late Flipkart deliveries are not on time.READ MORE']},\n",
       " {'Product Name': 'Lenovo IdeaPad Gaming 3 AMD Ryzen 5 Hexa Core 5500H - (8 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/N...',\n",
       "  'Price': '₹47,990',\n",
       "  'Rating': '3.7',\n",
       "  'Number of Ratings': '7',\n",
       "  'Number of Reviews': '1',\n",
       "  'Review Summary': ['Battery issue, rest is good'],\n",
       "  'Review Details': ['product is good with this price tag; RTX gpu is a plus point, battery life is very low around 2 hours (for only browsing)Bad thing about Flipkart is they give us old laptop whose battery is issued 3  months beforehandREAD MORE']},\n",
       " {'Product Name': 'Lenovo Legion 5 AMD Ryzen 7 Octa Core 5800H - (16 GB/1 TB SSD/Windows 11 Home/6 GB Graphics/NVIDIA GeF...',\n",
       "  'Price': '₹99,990',\n",
       "  'Rating': '4.6',\n",
       "  'Number of Ratings': '7',\n",
       "  'Number of Reviews': '0'},\n",
       " {'Product Name': 'Lenovo Legion 5 Pro AMD Ryzen 7 Octa Core 6800H - (32 GB/1 TB SSD/Windows 11 Home/8 GB Graphics/NVIDIA...',\n",
       "  'Price': '₹1,24,990',\n",
       "  'Rating': '4.3',\n",
       "  'Number of Ratings': '25',\n",
       "  'Number of Reviews': '1',\n",
       "  'Review Summary': ['Good choice'],\n",
       "  'Review Details': [\"Awesome laptop with a few niggles. The display is crisp and vibrant, the performance is top-notch. Including Windows Office and a 3-year Warranty is the icing on the cake. The niggle I want to mention is the weight (hefty) of the laptop and the charger brick (it's huge, takes a lot of space, and freaking heavy!). Other than that everything else is great.READ MORE\"]},\n",
       " {'Product Name': 'Lenovo Legion 5 Pro Intel Core i7 12th Gen 12700H - (32 GB/1 TB SSD/Windows 11 Home/8 GB Graphics/NVID...',\n",
       "  'Price': '₹1,44,990',\n",
       "  'Rating': 'No rating available',\n",
       "  'Number of Ratings': 'No ratings',\n",
       "  'Number of Reviews': 'No reviews'},\n",
       " {'Product Name': 'Lenovo Legion 5 Pro AMD Ryzen 7 Octa Core 5800H - (32 GB/1 TB SSD/Windows 11 Home/8 GB Graphics/NVIDIA...',\n",
       "  'Price': '₹1,19,990',\n",
       "  'Rating': '4.7',\n",
       "  'Number of Ratings': '3',\n",
       "  'Number of Reviews': '0'},\n",
       " {'Product Name': 'Lenovo Legion 5 AMD AMD Ryzen 7 Octa Core 5800H - (16 GB/512 GB SSD/Windows 11 Home/6 GB Graphics/NVID...',\n",
       "  'Price': '₹98,990',\n",
       "  'Rating': '4.4',\n",
       "  'Number of Ratings': '88',\n",
       "  'Number of Reviews': '18',\n",
       "  'Review Summary': ['Good quality product',\n",
       "   'Highly recommended',\n",
       "   'Worth every penny',\n",
       "   'Classy product',\n",
       "   'Very poor',\n",
       "   'Good choice',\n",
       "   'Wonderful',\n",
       "   'Must buy!',\n",
       "   'Delightful',\n",
       "   'Really Nice'],\n",
       "  'Review Details': [\"Very powerful gaming machine, but I highly recommend u to use cooling pads, as temperature rise above 100degrees .I was playing uncharted 4 in highest possible settings, I could easily get 60+ fps, but the CPU temp reached 100degrees.Another thing I noticed is the hinges are poor quality,i don't get the robust feel in it, it's been just 1 month and the hinges feel like I have opened and closed it for years and made it looseREAD MORE\",\n",
       "   'its just a beastREAD MORE',\n",
       "   \"It's an amazing product. I loved it ... It has better capacity to handle multiple tasking.READ MORE\",\n",
       "   'Value For Money 😁READ MORE',\n",
       "   \"After using 12days of this laptop. I'm facing screen shacking issue double pictures viewing issue, while playing videos picture are drifting. video viewing issue like pictures are shacking and half of the screen trend into black color.READ MORE\",\n",
       "   'Excellent product great performance and build quality. I wish they could have packed this device with a 1tb SSD. Otherwise, I am satisfied with this productREAD MORE',\n",
       "   'Great product at this price. I have been an Intel user since long and this is my first AMD laptop. It seriously packs a good punch when it comes to gaming. RTX 3060 with a 165 hz screen and 16GB ram works like a charm. No major heating issues as the fans work well. Have been playing God of War, AC Valhalla on Ultra and it is smooth. Only con I noticed is the sound by Nahimic is pretty low and you have literally put it on full volume. Also storage is 512GB SSD which is a downgrade for laptops...READ MORE',\n",
       "   'Great Laptop with top of the line specs got it for around 84k by exchanging old Dell laptop. If you got editing and graphic designing work and if you use blender and premiere pro just go for it! Really a great machineREAD MORE',\n",
       "   'It is a lovely looking machine  ....but it is too early to say anything about it is performance and hardware.READ MORE',\n",
       "   'This is really good machine for any work but you have any heavy graphic design work or your first priority is for gaming then you should go for this laptop. You will never disappoint about your purchase...👍READ MORE']},\n",
       " {'Product Name': 'Lenovo Legion 5 Pro AMD Ryzen 7 Octa Core 5800H - (16 GB/1 TB SSD/Windows 11 Home/6 GB Graphics/NVIDIA...',\n",
       "  'Price': '₹1,04,990',\n",
       "  'Rating': '4.5',\n",
       "  'Number of Ratings': '56',\n",
       "  'Number of Reviews': '7',\n",
       "  'Review Summary': ['Absolute rubbish!',\n",
       "   'Mind-blowing purchase',\n",
       "   'Wonderful',\n",
       "   'Did not meet expectations',\n",
       "   'Delightful',\n",
       "   'Awesome',\n",
       "   'Worth the money'],\n",
       "  'Review Details': [\"1 star rating is for Flipkart's smart upgrade plan under which I bought the Lenovo laptop. I have no issues with the laptop however have issues with the plan. It's utterly a useless plan by Flipkart. Please scrap it and will request users to not subscribe to it.READ MORE\",\n",
       "   'Absolute gemREAD MORE',\n",
       "   'Nice beastREAD MORE',\n",
       "   'The speaker 🔊 is not workingREAD MORE',\n",
       "   'Awesome LaptopREAD MORE',\n",
       "   \"One word, Beast! But don't except much on battery!READ MORE\",\n",
       "   'Awesome productREAD MORE']},\n",
       " {'Product Name': 'Lenovo Legion Slim 5 AMD Ryzen 7 Octa Core 7840HS - (16 GB/512 GB SSD/Windows 11 Home/8 GB Graphics/NV...',\n",
       "  'Price': '₹1,37,490',\n",
       "  'Rating': 'No rating available',\n",
       "  'Number of Ratings': 'No ratings',\n",
       "  'Number of Reviews': 'No reviews'},\n",
       " {'Product Name': 'Lenovo Legion 5 Pro AMD Ryzen 7 Octa Core 6800H - (16 GB/1 TB SSD/Windows 11 Home/6 GB Graphics/NVIDIA...',\n",
       "  'Price': '₹1,09,990',\n",
       "  'Rating': '4.1',\n",
       "  'Number of Ratings': '25',\n",
       "  'Number of Reviews': '3',\n",
       "  'Review Summary': ['Wonderful', 'Highly recommended', 'Must buy!'],\n",
       "  'Review Details': ['It exceeded my expectations. Its powerful performance, high refresh rate display, and sleek design make it a top-tier gaming laptop. The keyboard is comfortable, and the cooling system keeps things running smoothly. Overall, a solid investment for any gamer.READ MORE',\n",
       "   'Osm product... Beast performanceREAD MORE',\n",
       "   'the most value for money productREAD MORE']}]"
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "c99bcc03-6927-4f11-8e8d-3e29f21b18fa",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Product Name</th>\n",
       "      <th>Price</th>\n",
       "      <th>Rating</th>\n",
       "      <th>Number of Ratings</th>\n",
       "      <th>Number of Reviews</th>\n",
       "      <th>Review Summary</th>\n",
       "      <th>Review Details</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Lenovo IdeaPad Gaming 3 AMD Ryzen 5 Hexa Core ...</td>\n",
       "      <td>₹56,990</td>\n",
       "      <td>4.3</td>\n",
       "      <td>68</td>\n",
       "      <td>8</td>\n",
       "      <td>[Classy product, Worth the money, Horrible, Be...</td>\n",
       "      <td>[First Impression: Great build no wobble, full...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Lenovo IdeaPad Gaming 3 AMD Ryzen 5 Hexa Core ...</td>\n",
       "      <td>₹47,990</td>\n",
       "      <td>3.7</td>\n",
       "      <td>7</td>\n",
       "      <td>1</td>\n",
       "      <td>[Battery issue, rest is good]</td>\n",
       "      <td>[product is good with this price tag; RTX gpu ...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Lenovo Legion 5 AMD Ryzen 7 Octa Core 5800H - ...</td>\n",
       "      <td>₹99,990</td>\n",
       "      <td>4.6</td>\n",
       "      <td>7</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Lenovo Legion 5 Pro AMD Ryzen 7 Octa Core 6800...</td>\n",
       "      <td>₹1,24,990</td>\n",
       "      <td>4.3</td>\n",
       "      <td>25</td>\n",
       "      <td>1</td>\n",
       "      <td>[Good choice]</td>\n",
       "      <td>[Awesome laptop with a few niggles. The displa...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Lenovo Legion 5 Pro Intel Core i7 12th Gen 127...</td>\n",
       "      <td>₹1,44,990</td>\n",
       "      <td>No rating available</td>\n",
       "      <td>No ratings</td>\n",
       "      <td>No reviews</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>Lenovo Legion 5 Pro AMD Ryzen 7 Octa Core 5800...</td>\n",
       "      <td>₹1,19,990</td>\n",
       "      <td>4.7</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>Lenovo Legion 5 AMD AMD Ryzen 7 Octa Core 5800...</td>\n",
       "      <td>₹98,990</td>\n",
       "      <td>4.4</td>\n",
       "      <td>88</td>\n",
       "      <td>18</td>\n",
       "      <td>[Good quality product, Highly recommended, Wor...</td>\n",
       "      <td>[Very powerful gaming machine, but I highly re...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>Lenovo Legion 5 Pro AMD Ryzen 7 Octa Core 5800...</td>\n",
       "      <td>₹1,04,990</td>\n",
       "      <td>4.5</td>\n",
       "      <td>56</td>\n",
       "      <td>7</td>\n",
       "      <td>[Absolute rubbish!, Mind-blowing purchase, Won...</td>\n",
       "      <td>[1 star rating is for Flipkart's smart upgrade...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>Lenovo Legion Slim 5 AMD Ryzen 7 Octa Core 784...</td>\n",
       "      <td>₹1,37,490</td>\n",
       "      <td>No rating available</td>\n",
       "      <td>No ratings</td>\n",
       "      <td>No reviews</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>Lenovo Legion 5 Pro AMD Ryzen 7 Octa Core 6800...</td>\n",
       "      <td>₹1,09,990</td>\n",
       "      <td>4.1</td>\n",
       "      <td>25</td>\n",
       "      <td>3</td>\n",
       "      <td>[Wonderful, Highly recommended, Must buy!]</td>\n",
       "      <td>[It exceeded my expectations. Its powerful per...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                        Product Name      Price  \\\n",
       "0  Lenovo IdeaPad Gaming 3 AMD Ryzen 5 Hexa Core ...    ₹56,990   \n",
       "1  Lenovo IdeaPad Gaming 3 AMD Ryzen 5 Hexa Core ...    ₹47,990   \n",
       "2  Lenovo Legion 5 AMD Ryzen 7 Octa Core 5800H - ...    ₹99,990   \n",
       "3  Lenovo Legion 5 Pro AMD Ryzen 7 Octa Core 6800...  ₹1,24,990   \n",
       "4  Lenovo Legion 5 Pro Intel Core i7 12th Gen 127...  ₹1,44,990   \n",
       "5  Lenovo Legion 5 Pro AMD Ryzen 7 Octa Core 5800...  ₹1,19,990   \n",
       "6  Lenovo Legion 5 AMD AMD Ryzen 7 Octa Core 5800...    ₹98,990   \n",
       "7  Lenovo Legion 5 Pro AMD Ryzen 7 Octa Core 5800...  ₹1,04,990   \n",
       "8  Lenovo Legion Slim 5 AMD Ryzen 7 Octa Core 784...  ₹1,37,490   \n",
       "9  Lenovo Legion 5 Pro AMD Ryzen 7 Octa Core 6800...  ₹1,09,990   \n",
       "\n",
       "                Rating Number of Ratings Number of Reviews  \\\n",
       "0                  4.3                68                 8   \n",
       "1                  3.7                 7                 1   \n",
       "2                  4.6                 7                 0   \n",
       "3                  4.3                25                 1   \n",
       "4  No rating available        No ratings        No reviews   \n",
       "5                  4.7                 3                 0   \n",
       "6                  4.4                88                18   \n",
       "7                  4.5                56                 7   \n",
       "8  No rating available        No ratings        No reviews   \n",
       "9                  4.1                25                 3   \n",
       "\n",
       "                                      Review Summary  \\\n",
       "0  [Classy product, Worth the money, Horrible, Be...   \n",
       "1                      [Battery issue, rest is good]   \n",
       "2                                                NaN   \n",
       "3                                      [Good choice]   \n",
       "4                                                NaN   \n",
       "5                                                NaN   \n",
       "6  [Good quality product, Highly recommended, Wor...   \n",
       "7  [Absolute rubbish!, Mind-blowing purchase, Won...   \n",
       "8                                                NaN   \n",
       "9         [Wonderful, Highly recommended, Must buy!]   \n",
       "\n",
       "                                      Review Details  \n",
       "0  [First Impression: Great build no wobble, full...  \n",
       "1  [product is good with this price tag; RTX gpu ...  \n",
       "2                                                NaN  \n",
       "3  [Awesome laptop with a few niggles. The displa...  \n",
       "4                                                NaN  \n",
       "5                                                NaN  \n",
       "6  [Very powerful gaming machine, but I highly re...  \n",
       "7  [1 star rating is for Flipkart's smart upgrade...  \n",
       "8                                                NaN  \n",
       "9  [It exceeded my expectations. Its powerful per...  "
      ]
     },
     "execution_count": 18,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df = pd.DataFrame(data)\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "a0c14e4d-26a3-41d8-a67e-a1415b35f219",
   "metadata": {},
   "outputs": [],
   "source": [
    "df.to_csv('D:\\Customer Review Analysis Project\\scraped_data.csv', index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "778fb71a-e88e-4a85-8d4f-be17c72587a1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
